    cmake_version: "3.26.0"
    snort_install_dir: "/usr/local/snort"
    snort_config_dir: "{{ snort_install_dir }}/etc/snort"
    snort_rules_dir: "{{ snort_install_dir }}/etc/rules"
    interface: "eth0"
    home_net: "192.168.1.0/24"
    community_rules_url: "https://www.snort.org/downloads/community/community-rules.tar.gz"
    snort_user: "snort"
    snort_group: "snort"
    external_net: "!$HOME_NET"